#!/bin/sh

file=`find . -iname '*.ome.tif' | head -n 1`

# divide
source $HOME/.venv/ttr/bin/activate
mmdecsplit.py -g 415 0 $file

# set library path
FUSION_HOME="$HOME/bin/diSPIMFusion/cudaLib/"
#LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$FUSION_HOME/bin/linux"
RUN="$FUSION_HOME/bin/linux/spimFusion"

# set parameters
psf_a_filename="$FUSION_HOME/data/PSFA.tif"
psf_b_filename="$FUSION_HOME/data/PSFB.tif"
spim_a_folder="./SPIMA/"
spim_b_folder="./SPIMB/"
spim_a_prefix="SPIMA_"
spim_b_prefix="SPIMB_"
FTOL=0.0001
it_limit=30000
bits_per_sample=32
reg_mode=2
iteration=10
p_size_xy=0.1625
p_size_z=0.5

# A1
output_folder="Output_A1"
mkdir -p $output_folder

y_axis_rotation=1
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$FUSION_HOME/bin/linux" \
$RUN $output_folder $spim_a_folder $spim_b_folder $spim_a_prefix $spim_b_prefix 0 0 1 0 \
	$p_size_xy $p_size_xy $p_size_z $p_size_xy $p_size_xy $p_size_z \
	$reg_mode $y_axis_rotation 0 "Balabalabala" $FTOL $it_limit 1 1 \
	$psf_a_filename $psf_b_filename $iteration 0 0 1 0 0 $bits_per_sample 0 0



#$RUN -i1 $fileSPIMA -i2 $fileSPIMB -fp1 $filePSFA -fp2 $filePSFB \
#	-o "$folder/$fileDecon" \
#	-it $iteration -cOFF -imgrot $rotation -dev 0 -verbON -oreg1 \
#	"$folder/$fileRegA" -oreg2 "$folder/$fileRegB" -otmx "$folder/$fileoTmx"

