#!/bin/sh
source $HOME/.venv/gpu/bin/activate

iters=0
reg_method="full"
keep_channels=

# show usage and exit
function show_usage () {
    echo "$(basename "$0") [-x VIEW_X] [-m REG_METHOD] [-i ITER] [-k] file [file ...]"
    exit 1
}

# parse options
while getopts "x:m:i:k" OPT;
do
    case "$OPT" in
    x) view_x="$OPTARG" ;;
    m) reg_method="${OPTARG,,}" ;;
    k) keep_channels="-k" ;;
    i) iters="$OPTARG" ;;
     :) show_usage ;;
    \?) show_usage ;;
    esac
done
shift $((OPTIND - 1))

echo "$keep_channels"

# find an image file if not specified
if [ $# == 0 ]; then
    files=("$(find . -iname '*MMStack_Pos0.ome.tif' | head -n 1)")
else
    files=("$@")
fi

if [ $# == 0 ]; then
    files=("$(find . -iname '*MMStack_Pos0.ome.tif' | head -n 1)")
else
    files=("$@")
fi

for file in "${files[@]}"
do
    if [[ "$file" =~ '.ome.tif' ]]; then
        stem="$(echo ${file} | sed 's/\.ome\.tif$//')"
    elif [[ "$file" =~ '.tif' ]]; then
        stem="$(echo ${file} | sed 's/\.tif$//')"
    else
        echo "Not an image file: ${file}"
        continue
    fi
	output_crop="${stem}_crop_0.tif"
	output_fusion_0="${stem}_fusion_0.tif"
	output_fusion_1="${stem}_fusion_1.tif"

    if [[ "x${view_x}" == "x" ]]; then
        mmcrop.py -P 0 -o "$output_crop" "$file"
    else
        mmcrop.py -R "$view_x" 0 256 256 -o "$output_crop" "$file"
    fi

	# Main = A, Sub = B
	echo "Output ${output_fusion_0} for Path A"
	mmfusion.py -g 0 -m 0 -s 1 -i "$iters" -r -90 $keep_channels -e "${reg_method^}" -o "$output_fusion_0" "$output_crop"

	# Main = B, Sub = A
	echo "Output ${output_fusion_1} for Path B"
	mmfusion.py -g 0 -m 0 -s 1 -i "$iters" -r 90 $keep_channels -e "${reg_method^}" -o "$output_fusion_1" "$output_crop"


	# This worked for the sub channel acquired using Path B
	#mmfusion.py -g 0 -m 1 -s 0 -r -90 -e Full -o "$output_fusion_1" "$output_crop"
done

