#!/usr/bin/env bash
source $HOME/.venv/gpu/bin/activate

if [ $# == 0 ]; then
    files=("$(find . -iname '*MMStack_Pos0.ome.tif' | head -n 1)")
else
    files=("$@")
fi

for file in "${files[@]}"
do
    if [[ "$file" =~ '.ome.tif' ]]; then
        output="$(echo ${file} | sed 's/\.ome\.tif$/_drift.tif/')"
    elif [[ "$file" =~ '.tif' ]]; then
        output="$(echo ${file} | sed 's/\.tif$/_drift.tif/')"
    else
        echo "Not an image file: ${file}"
        continue
    fi
    mmregister.py -P 0 -g 0 -e Drift -A "$file"
    mmcrop.py "$output"
done
