#!/usr/bin/env bash
set -euo pipefail
source $HOME/.venv/gpu/bin/activate

iter=10
log_level='INFO'

# show usage and exit
function show_usage () {
    echo "$(basename "$0") [-i ITERATION] [-L LOG] file [file ...]"
    exit 1
}

# parse options
while getopts "i:L:" OPT;
do
    case "$OPT" in
    i) iter="$OPTARG" ;;
    L) log_level="$OPTARG" ;;
    :) show_usage ;;
    \?) show_usage ;;
    esac
done
shift $((OPTIND - 1))

# find an image file if not specified
if [ $# == 0 ]; then
    files=("$(find . -maxdepth 1 -iname '*_crop_1.tif' | head -n 1)")
else
    files=("$@")
fi

# process!
for file in "${files[@]}"
do
    if [[ "$file" =~ '.ome.tif' ]]; then
        stem="$(echo ${file} | sed 's/\.ome\.tif$//')"
    elif [[ "$file" =~ '.tif' ]]; then
        stem="$(echo ${file} | sed 's/\.tif$//')"
    else
        echo "Not an image file: ${file}"
        continue
    fi

    output_log="${stem}_deconv.log"
    echo "Deconvolution:" $(date) > $output_log

    scaling_option=""
	output_deconv="${stem}_deconv.tif"
    echo "Iteration: ${iter}" >> $output_log
    echo "Scaling: ${scaling_option}" >> $output_log
    mmdeconv.py -g 0 -i "$iter" $scaling_option -o "$output_deconv" -L "$log_level" "$file"

    scaling_option="-s"
	output_deconv="${stem}_deconv_iso.tif"
    echo "Iteration: ${iter}" >> $output_log
    echo "Scaling: ${scaling_option}" >> $output_log
    mmdeconv.py -g 0 -i "$iter" $scaling_option -o "$output_deconv" -L "$log_level" "$file"

    scaling_option="-s -r"
	output_deconv="${stem}_deconv_res.tif"
    echo "Iteration: ${iter}" >> $output_log
    echo "Scaling: ${scaling_option}" >> $output_log
    mmdeconv.py -g 0 -i "$iter" $scaling_option -o "$output_deconv" -L "$log_level" "$file"

done
