#!/usr/bin/env bash
set -euo pipefail
source $HOME/.venv/gpu/bin/activate

file_egfp=""
file_back=""
init_shift="-S 0 0 0"
rev_egfp=""
truncate=""
log_level='INFO'

# show usage and exit
function show_usage () {
    echo "$(basename "$0") [-e FILE_EGFP] [-s X Y Z] [-r] [-n] [-L LOG] FILE_BACK"
    exit 1
}

# parse options
while getopts "e:s:rnL:" OPT;
do
    case "$OPT" in
    e) file_egfp="$OPTARG" ;;
    s) init_shift="-S $OPTARG" ;;
    r) rev_egfp="-r" ;;
    n) truncate="-n" ;;
    L) log_level="$OPTARG" ;;
    :) show_usage ;;
    \?) show_usage ;;
    esac
done
shift $((OPTIND - 1))

# find the overlay image
if [[ "$file_egfp" == "" ]]; then
    #file_egfp="$(find . -maxdepth 1 -iname '*EGFP*MMStack_Pos0_crop_0.tif' | head -n 1)"
    file_egfp="$(find . -maxdepth 1 -iname 'MAX*EGFP*.tif' | head -n 1)"
fi

# find the background image 
if [[ "$#" == 0 ]]; then
    file_back="$(find . -maxdepth 1 -iname '*MMStack_Pos0_*_crop_1_deconv_res.tif' | head -n 1)"
    if [[ "$file_back" == "" ]]; then
        file_back="$(find . -maxdepth 1 -iname '*MMStack_Pos0_*_crop_1.tif' | head -n 1)"
    fi
elif [[ "$#" == 1 ]]; then
    file_back="$@"
else
    echo "More than one background files are specified."
    exit 1
fi

# getting stems
if [[ "$file_back" =~ '.ome.tif' ]]; then
    stem_back="$(echo ${file_back} | sed 's/\.ome\.tif$//')"
elif [[ "$file_back" =~ '.tif' ]]; then
    stem_back="$(echo ${file_back} | sed 's/\.tif$//')"
else
    echo "Not an image file: ${file_back}"
    exit 1
fi

if [[ "$file_egfp" =~ '.ome.tif' ]]; then
    stem_egfp="$(echo ${file_egfp} | sed 's/\.ome\.tif$//')"
elif [[ "$file_egfp" =~ '.tif' ]]; then
    stem_egfp="$(echo ${file_egfp} | sed 's/\.tif$//')"
else
    echo "Not an image file: ${file_egfp}"
    exit 1
fi

# process!
output_egfp_single="${stem_egfp}_single.tif"
output_overlay="${stem_back}_overlay.tif"

mmcrop.py -o "$output_egfp_single" $rev_egfp -c 0 -L "$log_level" "$file_egfp"
mmoverlay.py -g 0 -o "$output_overlay" -e None $init_shift $truncate -L "$log_level" "$output_egfp_single" "$file_back"


