#!/usr/bin/env bash
set -euo pipefail
source $HOME/.venv/gpu/bin/activate

proj_method='average'
proj_win=5
proj_slide=0
log_level='INFO'
keyword='fix100ms'
slide_option='-s'
dry_run=0

# show usage and exit
function show_usage () {
    echo "$(basename "$0") [-m METHOD] [-w WINDOW] [-L LOG] [-D] keyword"
    exit 1
}

# parse options
while getopts "m:w:L:D" OPT;
do
    case "$OPT" in
    m) proj_method="$OPTARG" ;;
    w) proj_win="$OPTARG" ;;
    D) dry_run=1 ;;
    L) log_level="$OPTARG" ;;
    :) show_usage ;;
    \?) show_usage ;;
    esac
done
shift $((OPTIND - 1))

# find folders using the keyword
if [[ $# > 0 ]]; then
    keyword="$1"
fi
glob="*${keyword}*"
readarray -t folders < <(find . -type d -iname "$glob")
current="$(pwd)"

for folder in "${folders[@]}"
do
    echo "***** ${folder} *****"
    if [[ $dry_run == 0 ]]; then
        cd "$current"
        cd "$folder"
        if [[ $(project -m "${proj_method}" -w "${proj_win}" $slide_option -L "${log_level}") -ne 0 ]]; then
            echo "Error while handling: ${folder}"
        fi
        echo "."
    fi
done
